// Video catalogue: entries are generated by scripts/ingest-videos.mjs
// (metadata + posters), categories are curated here.
import rawEntries from './videos.json';

export interface VideoEntry {
  title: string;
  category: string;
  tags: string[];
  file: string;
  poster: string;
  quality: string;
  duration: string;
  width: number;
  height: number;
}

export interface VideoCategory {
  id: string;
  label: string;
  description: string;
  /** Optional external repo / project link shown with the category. */
  link?: string;
  linkLabel?: string;
}

export const CATEGORIES: VideoCategory[] = [
  {
    id: 'engine',
    label: 'Morrow 引擎',
    description: '自研 Morrow 渲染引擎与实时渲染技术实验（尚未开源）',
  },
  {
    id: 'morrowui',
    label: 'MorrowUI',
    description: '开源车载 HMI 组件库的效果展示',
    link: 'https://github.com/yuhenmeili/MorrowUI',
    linkLabel: 'GitHub 开源仓库',
  },
  {
    id: 'auto',
    label: '车载 HMI',
    description: 'Unity 智能座舱演示',
  },
  {
    id: 'gis',
    label: 'GIS · 数字孪生',
    description: '三维地理信息、倾斜摄影与数字孪生场景',
  },
  {
    id: 'bimcad',
    label: 'BIM · CAD',
    description: '建筑信息模型与 CAD 数据的实时可视化',
  },
  {
    id: 'web',
    label: 'Web · 应用',
    description: '浏览器端轻量化渲染与线上 3D 应用',
  },
];

export const VIDEOS: VideoEntry[] = rawEntries as VideoEntry[];

export function categoryLabel(id: string): string {
  return CATEGORIES.find((c) => c.id === id)?.label ?? id;
}

export function categoryById(id: string): VideoCategory | undefined {
  return CATEGORIES.find((c) => c.id === id);
}
