// Video catalogue: entries are generated by scripts/ingest-videos.mjs
// (metadata + posters), categories are curated here.
import rawEntries from './videos.json';

export interface VideoEntry {
  title: string;
  category: string;
  tags: string[];
  file: string;
  poster: string;
  quality: string;
  duration: string;
  width: number;
  height: number;
}

export interface VideoCategory {
  id: string;
  label: string;
  description: string;
  /** Optional external repo / project link shown with the category. */
  link?: string;
  linkLabel?: string;
}

export const CATEGORIES: VideoCategory[] = [
  {
    id: 'engine',
    label: 'Morrow 引擎',
    description: '自研 Vulkan 渲染引擎：地形、体积雾、粒子等整体效果（尚未开源）',
  },
  {
    id: 'morrowui',
    label: 'MorrowUI',
    description: '开源车载 HMI 引擎的组件与效果展示',
    link: 'https://github.com/yuhenmeili/MorrowUI',
    linkLabel: 'GitHub 开源仓库',
  },
  {
    id: 'unity',
    label: 'Unity',
    description: 'Unity 智能座舱演示',
  },
  {
    id: 'threejs',
    label: 'Three.js',
    description: '基于 Three.js 的 Web 3D 应用与渲染技术',
  },
  {
    id: 'cesium',
    label: 'Cesium',
    description: '基于 Cesium 的 GIS 与数字孪生场景',
  },
];

export const VIDEOS: VideoEntry[] = rawEntries as VideoEntry[];

export function categoryLabel(id: string): string {
  return CATEGORIES.find((c) => c.id === id)?.label ?? id;
}

export function categoryById(id: string): VideoCategory | undefined {
  return CATEGORIES.find((c) => c.id === id);
}
