// Video catalogue: entries are generated by scripts/ingest-videos.mjs
// (metadata + posters), categories are curated here.
import rawEntries from './videos.json';

export interface VideoEntry {
  slug: string;
  title: string;
  category: string;
  tags: string[];
  file: string;
  poster: string;
  quality: string;
  duration: string;
  width: number;
  height: number;
}

export interface VideoCategory {
  id: string;
  label: string;
  description: string;
}

export const CATEGORIES: VideoCategory[] = [
  {
    id: 'engine',
    label: '自研引擎',
    description: '自研 Vulkan 渲染引擎与实时渲染技术实验',
  },
  {
    id: 'auto',
    label: '车载 HMI',
    description: 'MorrowUI 车载界面动效与 Unity 智能座舱演示',
  },
  {
    id: 'gis',
    label: 'GIS · 数字孪生',
    description: '三维地理信息、倾斜摄影与数字孪生场景',
  },
  {
    id: 'bimcad',
    label: 'BIM · CAD',
    description: '建筑信息模型与 CAD 数据的实时可视化',
  },
  {
    id: 'web',
    label: 'Web · 应用',
    description: '浏览器端轻量化渲染与线上 3D 应用',
  },
];

export const VIDEOS: VideoEntry[] = rawEntries as VideoEntry[];

export function categoryLabel(id: string): string {
  return CATEGORIES.find((c) => c.id === id)?.label ?? id;
}
